// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPMfRDZ-U-ZHRvfxuTAF0zBIh48mbB2dg',
    appId: '1:737953122673:web:d558758c4dc38d991e0ed0',
    messagingSenderId: '737953122673',
    projectId: 'class-activity13',
    authDomain: 'class-activity13.firebaseapp.com',
    storageBucket: 'class-activity13.firebasestorage.app',
    measurementId: 'G-JLFYF9V5BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX2kHRN2XqBd44S8fpB7ssw6XyUHGUYls',
    appId: '1:737953122673:android:cb22cec73dc490dd1e0ed0',
    messagingSenderId: '737953122673',
    projectId: 'class-activity13',
    storageBucket: 'class-activity13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4HAycNg2fI7LGBAGX0Qo-vLOx8NCkYE',
    appId: '1:737953122673:ios:6ed72cf2eab731f11e0ed0',
    messagingSenderId: '737953122673',
    projectId: 'class-activity13',
    storageBucket: 'class-activity13.firebasestorage.app',
    iosBundleId: 'com.example.classActivity13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe4HAycNg2fI7LGBAGX0Qo-vLOx8NCkYE',
    appId: '1:737953122673:ios:6ed72cf2eab731f11e0ed0',
    messagingSenderId: '737953122673',
    projectId: 'class-activity13',
    storageBucket: 'class-activity13.firebasestorage.app',
    iosBundleId: 'com.example.classActivity13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPMfRDZ-U-ZHRvfxuTAF0zBIh48mbB2dg',
    appId: '1:737953122673:web:29aee606568ac39b1e0ed0',
    messagingSenderId: '737953122673',
    projectId: 'class-activity13',
    authDomain: 'class-activity13.firebaseapp.com',
    storageBucket: 'class-activity13.firebasestorage.app',
    measurementId: 'G-6YZG3MT4VT',
  );
}
